export interface Test {
  id: string;
  name: string;
  category: string;
  price: number;
  unit: string;
}

export interface TestPackage {
  id: string;
  name: string;
  testIds: string[];
  testPrices: { [testId: string]: number };
  originalPrice: number;
  discountPercentage: number;
  totalPrice: number;
}

export const initialTests: Test[] = [
  { id: '1', name: 'Tam Kan Sayımı', category: 'Laboratuvar', price: 150, unit: '₺' },
  { id: '2', name: 'Biyokimya Paneli', category: 'Laboratuvar', price: 250, unit: '₺' },
  { id: '3', name: 'Göğüs Röntgeni', category: 'Görüntüleme', price: 200, unit: '₺' },
  { id: '4', name: 'EKG', category: 'Kardiyoloji', price: 180, unit: '₺' },
  { id: '5', name: 'Spirometri', category: 'SFT', price: 220, unit: '₺' },
  { id: '6', name: 'Odyometri', category: 'Odyometri', price: 300, unit: '₺' },
  { id: '7', name: 'Göz Muayenesi', category: 'Göz', price: 150, unit: '₺' },
  { id: '8', name: 'Aşı Takibi', category: 'Aşı', price: 100, unit: '₺' },
];

export const initialPackages: TestPackage[] = [];

export const categories = ['Tümü', 'Laboratuvar', 'Görüntüleme', 'Kardiyoloji', 'SFT', 'Odyometri', 'Göz', 'Aşı'];

import { Personnel } from '../types/common';
import { ChartData } from '../types/dashboard';

export const chartData: ChartData[] = [
  { name: 'Oca', tarama: 140 },
  { name: 'Şub', tarama: 180 },
  { name: 'Mar', tarama: 250 },
  { name: 'Nis', tarama: 210 },
  { name: 'May', tarama: 290 },
  { name: 'Haz', tarama: 380 },
  { name: 'Tem', tarama: 320 },
];

export const recentScreenings: Personnel[] = [
  {
    id: 'PT-10492',
    name: 'Mehmet Yılmaz',
    companyId: 'COMP-001',
    companyName: 'ABC Lojistik A.Ş.',
    screeningType: 'İşe Giriş' as any,
    status: 'Temiz' as any,
    recordNumber: 'PT-10492',
  },
  {
    id: 'PT-10491',
    name: 'Ayşe Demir',
    companyId: 'COMP-002',
    companyName: 'TechNova Yazılım',
    screeningType: 'Periyodik' as any,
    status: 'İncelemede' as any,
    recordNumber: 'PT-10491',
  },
  {
    id: 'PT-10490',
    name: 'Can Korkmaz',
    companyId: 'COMP-003',
    companyName: 'Gama Üretim',
    screeningType: 'Periyodik' as any,
    status: 'Sevk Edildi' as any,
    recordNumber: 'PT-10490',
  },
  {
    id: 'PT-10489',
    name: 'Fatma Şahin',
    companyId: 'COMP-001',
    companyName: 'ABC Lojistik A.Ş.',
    screeningType: 'İşe Giriş' as any,
    status: 'Temiz' as any,
    recordNumber: 'PT-10489',
  },
  {
    id: 'PT-10488',
    name: 'Ali Yıldız',
    companyId: 'COMP-004',
    companyName: 'Delta Endüstri',
    screeningType: 'Periyodik' as any,
    status: 'Temiz' as any,
    recordNumber: 'PT-10488',
  },
];

export const timelineItems = [
  {
    time: '09:00',
    title: 'ABC Lojistik A.Ş.',
    desc: '32 İşe Giriş Taraması',
    status: 'completed' as const,
  },
  {
    time: '11:30',
    title: 'TechNova Yazılım',
    desc: '15 Periyodik Tarama',
    status: 'current' as const,
  },
  {
    time: '14:00',
    title: 'Gama Üretim Tesisleri',
    desc: 'Risk Değerlendirme ve Saha Gezisi',
    status: 'upcoming' as const,
  },
  {
    time: '16:30',
    title: 'Kurul Toplantısı',
    desc: 'Haziran Ayı İSG Kurulu İştiraki',
    status: 'upcoming' as const,
  },
];

// Personel tipleri ve mock data
export interface Staff {
  id: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  position: string;
  startDate: string;
  status: 'active' | 'inactive';
  avatar?: string;
}

export const staffPositions = [
  'Tümü',
  'Radyoloji Teknikeri',
  'Odyometrist',
  'Hemşire',
  'Laboratuvar Teknikeri',
  'Sağlık Teknikeri',
  'İş Yeri Hekimi',
  'Müdür',
  'Yönetici',
];

export const initialStaff: Staff[] = [
  {
    id: 'ST-001',
    firstName: 'Ahmet',
    lastName: 'Yılmaz',
    phone: '05321234567',
    email: 'ahmet.yilmaz@osgb.com',
    position: 'İş Yeri Hekimi',
    startDate: '2023-01-15',
    status: 'active',
  },
  {
    id: 'ST-002',
    firstName: 'Ayşe',
    lastName: 'Demir',
    phone: '05321234568',
    email: 'ayse.demir@osgb.com',
    position: 'Hemşire',
    startDate: '2023-03-20',
    status: 'active',
  },
  {
    id: 'ST-003',
    firstName: 'Mehmet',
    lastName: 'Kaya',
    phone: '05321234569',
    email: 'mehmet.kaya@osgb.com',
    position: 'Radyoloji Teknikeri',
    startDate: '2023-05-10',
    status: 'active',
  },
  {
    id: 'ST-004',
    firstName: 'Fatma',
    lastName: 'Şahin',
    phone: '05321234570',
    email: 'fatma.sahin@osgb.com',
    position: 'Odyometrist',
    startDate: '2023-06-01',
    status: 'active',
  },
  {
    id: 'ST-005',
    firstName: 'Ali',
    lastName: 'Öztürk',
    phone: '05321234571',
    email: 'ali.ozturk@osgb.com',
    position: 'Laboratuvar Teknikeri',
    startDate: '2023-07-15',
    status: 'active',
  },
  {
    id: 'ST-006',
    firstName: 'Zeynep',
    lastName: 'Çelik',
    phone: '05321234572',
    email: 'zeynep.celik@osgb.com',
    position: 'Sağlık Teknikeri',
    startDate: '2023-08-20',
    status: 'active',
  },
  {
    id: 'ST-007',
    firstName: 'Mustafa',
    lastName: 'Arslan',
    phone: '05321234573',
    email: 'mustafa.arslan@osgb.com',
    position: 'Müdür',
    startDate: '2022-01-01',
    status: 'active',
  },
  {
    id: 'ST-008',
    firstName: 'Elif',
    lastName: 'Kara',
    phone: '05321234574',
    email: 'elif.kara@osgb.com',
    position: 'Yönetici',
    startDate: '2022-03-15',
    status: 'active',
  },
];

export interface Company {
  id: string;
  name: string;
  taxNumber: string;
  taxOffice: string;
  authorizedPerson: string;
  authorizedPersonPhone: string;
  authorizedPersonEmail: string;
  employeeCount: number;
  address: string;
  sector: string;
  status: 'active' | 'inactive';
  createdAt: string;
}

export const initialCompanies: Company[] = [
  {
    id: 'CMP-001',
    name: 'Teknoloji A.Ş.',
    taxNumber: '1234567890',
    taxOffice: 'Büyükçekmece Vergi Dairesi',
    authorizedPerson: 'Ahmet Yılmaz',
    authorizedPersonPhone: '05321234567',
    authorizedPersonEmail: 'ahmet.yilmaz@teknoloji.com',
    employeeCount: 150,
    address: 'Teknopark Bulvarı No: 123, İstanbul',
    sector: 'Teknoloji',
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'CMP-002',
    name: 'Sağlık Hizmetleri Ltd. Şti.',
    taxNumber: '0987654321',
    taxOffice: 'Kadıköy Vergi Dairesi',
    authorizedPerson: 'Ayşe Demir',
    authorizedPersonPhone: '05329876543',
    authorizedPersonEmail: 'ayse.demir@saglikhizmetleri.com',
    employeeCount: 75,
    address: 'Sağlık Caddesi No: 45, İstanbul',
    sector: 'Sağlık',
    status: 'active',
    createdAt: '2024-02-20',
  },
  {
    id: 'CMP-003',
    name: 'İnşaat Yapı San. Tic. A.Ş.',
    taxNumber: '1122334455',
    taxOffice: 'Beşiktaş Vergi Dairesi',
    authorizedPerson: 'Mehmet Kaya',
    authorizedPersonPhone: '05334567890',
    authorizedPersonEmail: 'mehmet.kaya@insaatyapi.com',
    employeeCount: 200,
    address: 'İnşaat Sokak No: 78, İstanbul',
    sector: 'İnşaat',
    status: 'active',
    createdAt: '2024-03-10',
  },
  {
    id: 'CMP-004',
    name: 'Eğitim ve Danışmanlık Hizmetleri',
    taxNumber: '5566778899',
    taxOffice: 'Şişli Vergi Dairesi',
    authorizedPerson: 'Zeynep Aksoy',
    authorizedPersonPhone: '05342345678',
    authorizedPersonEmail: 'zeynep.aksoy@egitim.com',
    employeeCount: 30,
    address: 'Eğitim Bulvarı No: 12, İstanbul',
    sector: 'Eğitim',
    status: 'active',
    createdAt: '2024-04-05',
  },
  {
    id: 'CMP-005',
    name: 'Gıda Sanayi ve Ticaret Ltd. Şti.',
    taxNumber: '9988776655',
    taxOffice: 'Üsküdar Vergi Dairesi',
    authorizedPerson: 'Ali Çelik',
    authorizedPersonPhone: '05353456789',
    authorizedPersonEmail: 'ali.celik@gida.com',
    employeeCount: 120,
    address: 'Gıda Caddesi No: 56, İstanbul',
    sector: 'Gıda',
    status: 'inactive',
    createdAt: '2024-05-15',
  },
];

export const companySectors = [
  'Tümü',
  'Teknoloji',
  'Sağlık',
  'İnşaat',
  'Eğitim',
  'Gıda',
  'Üretim',
  'Hizmet',
  'Perakende',
  'Finans',
  'Enerji',
  'Ulaşım',
  'Lojistik',
  'Turizm',
  'Otomotiv',
  'Kimya',
  'Tekstil',
  'Madencilik',
  'Tarım',
  'Medya',
  'Telekomünikasyon',
  'Danışmanlık',
  'Avukatlık',
  'Mimarlık',
  'Mühendislik',
  'Reklamcılık',
  'Eğlence',
  'Spor',
  'Sanat',
  'Kültür',
  'Güvenlik',
  'Çevre',
  'Bilgi Teknolojileri',
  'Yazılım',
  'Donanım',
  'Elektronik',
  'Otomasyon',
  'Robotik',
  'Yapay Zeka',
  'Büyük Veri',
  'Bulut Bilişim',
  'Siber Güvenlik',
  'Blockchain',
  'E-Ticaret',
  'Dijital Pazarlama',
  'Sosyal Medya',
  'Mobil Uygulama',
  'Oyun',
  'Metaverse',
  'NFT',
  'Kripto Para',
  'FinTech',
  'Sağlık Teknolojileri',
  'MedTech',
  'BiyoTeknoloji',
  'Farmasötik',
  'Tıbbi Cihazlar',
  'Sağlık Hizmetleri',
  'Hastane',
  'Klinik',
  'Laboratuvar',
  'Eczane',
  'Sigorta',
  'Bankacılık',
  'Yatırım',
  'Portföy Yönetimi',
  'Risk Yönetimi',
  'Muhasebe',
  'Denetim',
  'Vergi',
  'Hukuk',
  'İnsan Kaynakları',
  'Pazarlama',
  'Satış',
  'Üretim Planlama',
  'Tedarik Zinciri',
  'Lojistik Yönetimi',
  'Depolama',
  'Dağıtım',
  'İhracat',
  'İthalat',
  'Gümrük',
  'Kargo',
  'Deniz Taşımacılığı',
  'Havayolu',
  'Demiryolu',
  'Karayolu',
  'Otobüs',
  'Taksi',
  'Kiralama',
  'Turizm İşletmeciliği',
  'Otel',
  'Restoran',
  'Kafe',
  'Bar',
  'Gezi',
  'Seyahat Acentesi',
  'Rehberlik',
  'Etkinlik Yönetimi',
  'Konferans',
  'Seminer',
  'Workshop',
  'Eğitim Merkezi',
  'Kurs',
  'Dersane',
  'Üniversite',
  'Okul',
  'Anaokulu',
  'Kreş',
  'Özel Ders',
  'Online Eğitim',
  'Uzaktan Eğitim',
  'E-Öğrenme',
  'MOOC',
  'Sertifika Programı',
  'Lisans Programı',
  'Yüksek Lisans',
  'Doktora',
  'Araştırma',
  'Geliştirme',
  'İnovasyon',
  'Patent',
  'Telif Hakkı',
  'Marka',
  'Tasarım',
  'Endüstriyel Tasarım',
  'Grafik Tasarım',
  'Web Tasarım',
  'UI/UX Tasarım',
  'Ürün Tasarımı',
  'Mimarlık Tasarımı',
  'İç Mimarlık',
  'Peyzaj Tasarımı',
  'Şehir Planlama',
  'Kentsel Dönüşüm',
  'Sürdürülebilirlik',
  'Yeşil Enerji',
  'Güneş Enerjisi',
  'Rüzgar Enerjisi',
  'Hidroelektrik',
  'Biyokütle',
  'Jeotermal',
  'Nükleer',
  'Atık Yönetimi',
  'Geri Dönüşüm',
  'Su Yönetimi',
  'Hava Kalitesi',
  'İklim Değişikliği',
  'Karbon Ayak İzi',
  'Çevre Etki Değerlendirmesi',
  'Çevre Mühendisliği',
  'Kimya Mühendisliği',
  'Makine Mühendisliği',
  'Elektrik Mühendisliği',
  'Elektronik Mühendisliği',
  'Bilgisayar Mühendisliği',
  'Yazılım Mühendisliği',
  'Endüstri Mühendisliği',
  'İnşaat Mühendisliği',
  'Mimarlık Mühendisliği',
  'Jeoloji Mühendisliği',
  'Maden Mühendisliği',
  'Metalurji Mühendisliği',
  'Gıda Mühendisliği',
  'Tekstil Mühendisliği',
  'Kimya Mühendisliği',
  'Enerji Mühendisliği',
  'Çevre Mühendisliği',
  'Biyomedikal Mühendisliği',
  'Genetik Mühendisliği',
  'Nanoteknoloji',
  'Malzeme Bilimi',
  'Fizik',
  'Kimya',
  'Biyoloji',
  'Matematik',
  'İstatistik',
  'Ekonomi',
  'İşletme',
  'Yönetim',
  'Pazarlama',
  'Finans',
  'Muhasebe',
  'Hukuk',
  'Siyaset',
  'Sosyoloji',
  'Psikoloji',
  'Eğitim',
  'Sanat',
  'Tarih',
  'Coğrafya',
  'Felsefe',
  'Dil',
  'Edebiyat',
  'Müzik',
  'Tiyatro',
  'Sinema',
  'Görsel Sanatlar',
  'Fotoğrafçılık',
  'Video Prodüksiyonu',
  'Animasyon',
  'Oyun Geliştirme',
  'Yazılım Geliştirme',
  'Web Geliştirme',
  'Mobil Geliştirme',
  'Bulut Geliştirme',
  'Veri Bilimi',
  'Yapay Zeka Geliştirme',
  'Makine Öğrenmesi',
  'Derin Öğrenme',
  'Doğal Dil İşleme',
  'Görüntü İşleme',
  'Ses İşleme',
  'Robotik',
  'Otomasyon',
  'İnternet of Things',
  'Blockchain Geliştirme',
  'Kripto Geliştirme',
  'Siber Güvenlik Geliştirme',
  'Ağ Güvenliği',
  'Uygulama Güvenliği',
  'Veri Güvenliği',
  'Bilgi Güvenliği',
  'Gizlilik',
  'KVKK',
  'GDPR',
  'Siber Suç',
  'Dijital Suç',
  'Siber Savaş',
  'Siber İstihbarat',
  'Siber Savunma',
  'Siber Saldırı',
  'Siber Koruması',
  'Siber Tehdit',
  'Siber Risk',
  'Siber Yönetişim',
  'Siber Strateji',
  'Siber Politika',
  'Siber Düzenleme',
  'Siber Standart',
  'Siber Sertifika',
  'Siber Eğitim',
  'Siber Farkındalık',
  'Siber Kültür',
  'Siber Etik',
  'Siber Hukuk',
  'Siber Suistimal',
  'Siber İstismar',
  'Siber Taciz',
  'Siber Zorbalık',
  'Siber Ağaç',
  'Siber Orman',
  'Siber Okyanus',
  'Siber Uzay',
  'Siber Evren',
  'Siber Dünya',
  'Siber Gezegen',
  'Siber Galaksi',
  'Siber Evren',
];
